import { APP_NAME, PRELAUNCH_NAME } from './constants'

export const FAQS = [
  {
    question: `What's ${APP_NAME}?`,
    answer: `${APP_NAME} is a platform for home cooks to discover, cook, and enjoy recipes. You can build your pantry, share your recipes, and match with community recipes.`,
  },
  {
    question: `What is ${PRELAUNCH_NAME} Mode?`,
    answer: `${APP_NAME} is in ${PRELAUNCH_NAME} mode. All subscription plans are locked until the official launch. Founder tiers are available and need your early support. As each tier sells out, new features are unlocked. This is done to fund the development of the platform and to reward early supporters.`,
  },
  {
    question: `What is the Founder's Edition?`,
    answer: `The Founder's Edition is a limited-time offer available during ${PRELAUNCH_NAME} mode. Founders receive a lifetime subscription to ${APP_NAME} and a special badge and other perks`,
  },
  {
    question: `${PRELAUNCH_NAME} mode: What are stretch goals?`,
    answer: `Stretch goals are additional features that we will unlock as we reach certain funding milestones and depending on development feasibility. They aren't promised, but we'd really like to see them happen.`,
  },
  {
    question: `How do I monetize my community?`,
    answer: `As a Hubbardly Blue member, your community participates in the revenue share program. You earn a percentage of the revenue generated by your community based on usage and activity.`,
  },
  {
    question: `How does the affiliate program work?`,
    answer: `The affiliate program is a way for you to earn money by referring others to ${APP_NAME}. You will receive a unique link to share with your friends and followers. When someone signs up using your link, you will receive a commission on their subscription. Check out <a href="/affiliate" class="link">our affiliate page</a> for more information.`,
  },
  {
    question: `How do I get started?`,
    answer: `Create an account. Choose a support tier and join in the funding of ${APP_NAME} if you can. Otherwise, sit tight while we get organized and we'll send you updates. In the meantime, join our Discord community to meet other home cooks and share recipes.`,
  },
  {
    question: `How do I join the Discord community?`,
    answer: `Join our Discord community by visiting <a href="/support" class="link">the support page</a>.`,
  },
  {
    question: `What is the blue check mark?`,
    answer: `The blue check mark is a badge of honor. It signifies that you are a premium user and have access to all Hubbardly features.`,
  },
  {
    question: `What's your refund policy?`,
    answer: `Short version: We only want your money if you are happy. If you are not happy, we will refund your money. Long version: <a href="/cancel" class="link">our refund and cancellation policy</a>. While we are in ${PRELAUNCH_NAME} mode, we are not offering refunds. However, if you really have a change of heart, of course we will refund your money. You'll lose your place in line though, and many not get another chance to become a Founder. Also, if we decide to cancel the project for any reason, we will refund your money.`,
  },
  {
    question: `Post-launch: How do I share my recipes?`,
    answer: `Once you have an account, you can create recipes and share them with the community.`,
  },
  {
    question: `Post-launch: How do I match with community recipes?`,
    answer: `Add items to your pantry and ${APP_NAME} will show you recipes that you can make with those items across the Community, including your own recipes.`,
  },
  {
    question: `Post-launch: How do I create recipes?`,
    answer: `Once you have an account, you can create recipes by adding ingredients and instructions.`,
  },
  {
    question: `Post-launch: How do I get access to all community recipes?`,
    answer: `Community recipes with three or fewer ingredients are available to all users. To get access to all community recipes, you need to subscribe to the Blue plan.`,
  },
]
