import { APP_NAME, FOUNDERS_NAME, PREMIUM_NAME } from './constants'
import { FOUNDER_FEATURES } from './features'

export const PLANS = {
  free: {
    name: `Free Forever`,
    price: `Free Forever`,
    slug: `free`,
    summary: `You're on the basic Free plan. Upgrade to Blue to unlock all community recipes.`,
    qtyMax: 0,
    description: `Free forever. Use ${APP_NAME} to build your pantry and share your recipes with the world.`,
    checkoutUrl: ``,
    isPrelaunch: false,
    isPremium: false,
    isDefault: true,
    bonusFeatures: {},
  },
  [`monthly`]: {
    name: `Blue Monthly`,
    price: `19/mo`,
    slug: `pro-monthly`,
    summary: `You're on the monthly Blue plan. Thank you for supporting ${APP_NAME}!`,
    isPrelaunch: false,
    description: `Unlock the full potential of ${APP_NAME} with ${PREMIUM_NAME}. You get a blue check mark and premium features for ultimate recipe creation and discovery.`,
    checkoutUrl: ``,
    qtyMax: 0,
    isPremium: true,
    isDefault: false,
    bonusFeatures: {},
  },
  [`annual`]: {
    name: `Blue Annual`,
    price: `199/yr`,
    slug: `pro-annual`,
    checkoutUrl: ``,
    summary: `You're on the annual Blue plan. Thank you for supporting ${APP_NAME}!`,
    isPrelaunch: false,
    description: `Unlock the full potential of ${APP_NAME} with ${PREMIUM_NAME}. You get a blue check mark and premium features for ultimate recipe creation and discovery.`,
    qtyMax: 0,
    isPremium: true,
    isDefault: false,
    bonusFeatures: {},
  },
  founder: {
    name: FOUNDERS_NAME,
    price: `299 once, use forever`,
    slug: `founder`,
    checkoutUrl: `https://rootrivals.lemonsqueezy.com/buy/3dbf3220-e3f3-4cc5-aa5a-765a9e5bf306`,
    summary: `What an absolute Chad! You're in ${APP_NAME} for life!`,
    description: `Super elite! ${APP_NAME} for life. The ${FOUNDERS_NAME} is our way of saying thanks for supporting ${APP_NAME} in these early days. These are rare, so get them while they last!`,
    qtyMax: 500,
    isPremium: true,
    isPrelaunch: true,
    isDefault: false,
    bonusFeatures: FOUNDER_FEATURES,
  },
}
